# Generated by Django 3.0.4 on 2020-05-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlestick',
            name='type',
            field=models.IntegerField(choices=[(0, 'regular'), (1, 'day')], default=1),
        ),
    ]
