# Generated by Django 3.0.4 on 2020-05-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0003_auto_20200519_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestick',
            name='volume_btc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='volume_currency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='weighted_price',
            field=models.FloatField(null=True),
        ),
    ]
