# Generated by Django 3.0.4 on 2020-05-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0004_auto_20200519_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestick',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='candlestick',
            unique_together={('datetime', 'type')},
        ),
    ]
